---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Home", href: "https://elaineyanxi-chen.github.io/p8105-finalproject.github.io/index.html", align: left }
    theme: journal
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include = FALSE}
library(tidyverse)
library(plotly)
library(tigris)
library(shiny)
library(flexdashboard)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r map data import, include=FALSE}
ny_counties <-
  counties(state = "36", cb = TRUE, resolution = "20m") %>% 
  janitor::clean_names()

ny_abortion_year = 
  read_csv(file = "data/NY_year_county.csv") %>%
  transform(borough = gsub(pattern = "Brooklyn", replacement = "Kings", borough)) %>%
  transform(borough = gsub(pattern = "Manhattan", replacement = "New York", borough)) %>%
  transform(borough = gsub(pattern = "Staten Island", replacement = "Richmond", borough)) %>%
  transform(borough = gsub(pattern = "Essex/Hamilton", replacement = "Essex", borough)) %>%
  transform(borough = gsub(pattern = "St Lawrence", replacement = "St. Lawrence", borough)) %>% 
  rename(name = borough) 

ny_year_geo <- 
  full_join(ny_counties, ny_abortion_year, by = "name") %>%
  select(name, total, year, geometry) %>% 
  filter(name != "Hamilton/Essex") %>% filter(name != "New York State") %>%
  filter(name != "New York City") %>% 
  mutate(
    name = replace(name, name == "Richmond", "Staten Island"), 
    name = replace(name, name == "Kings", "Brooklyn"),
    name = replace(name, name == "New York", "Manhattan")
  )
```


```{r age data import, include = FALSE}
merged_data = read_csv("data/master.csv")

merged_age = 
  merged_data %>% 
  select(borough, age_less_20:age_plus_40) %>% 
    pivot_longer(
      age_less_20:age_plus_40,
      names_to = "age", 
      values_to = "abortion",
      names_prefix = "age_"
    ) %>% 
    mutate(
      age = replace(age, age == "less_20", "<20"),
      age = replace(age, age == "20_24", "20-24"),
      age = replace(age, age == "25_29", "25-29"),
      age = replace(age, age == "30_34", "30-34"),
      age = replace(age, age == "35_39", "35-39"),
      age = replace(age, age == "plus_40", "40+"),
      age = factor(age)
    )
```


```{r race data import, include=FALSE}
merged_race = 
  merged_data %>% 
  select(borough, nh_white_only_ratio:h_total) %>% 
  pivot_longer(
      nh_white_only_ratio:h_total,
      names_to = "race", 
      values_to = "abortion"
    ) %>% 
    mutate(
      race = replace(race, race == "nh_white_only_ratio", "Non-Hispanic White"),
      race = replace(race, race == "nh_black_only_ratio", "Non-Hispanic Black"),
      race = replace(race, race == "nh_other_ratio", "Non-Hispanic Other"),
      race = replace(race, race == "h_total", "Hispanic"),
      race = factor(race)
    )
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r sidebar}
sliderInput(
  inputId = "year_choice",
  label = h3("Year"),
  min = 2014, max = 2019, value = 2014, sep = ""
)

age = merged_age %>% distinct(age) %>% pull()

selectInput(
  inputId = "age_choice",
  label = h3("Age"),
  choices = age,
  selected = "<20"
)

race = merged_race %>% distinct(race) %>% pull()

radioButtons(
  inputId = "race_choice",
  label = h3("Race"),
  choices = race,
  selected = "Non-Hispanic White"
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Rates of Abortion Across the Years in Counties within New York State


```{r map}
renderPlotly({
  ny_year_geo %>% 
    filter(year == input[["year_choice"]]) %>% 
      ggplot() +
        geom_sf(aes(fill = total, text = paste(name, total), colors = "viridis"))            
})
```


Column {data-width=350}
-----------------------------------------------------------------------

### Abortions Ratios in New York State Counties by Age

```{r age}
renderPlotly({
  merged_age %>% 
    filter(age == input[["age_choice"]]) %>% 
    mutate(borough = fct_reorder(borough, abortion)) %>% 
    plot_ly(x = ~borough, y = ~abortion, color = ~borough, colors = "viridis", type = "bar") %>% 
    layout(
      xaxis = list(title = "County"),
      yaxis = list(title = 'Induced Abortions 
                   per 1,000 Live Births'))
}) 
```

### Abortions Ratios in New York State Counties by Race

```{r race}
renderPlotly({
  merged_race %>% 
    filter(race == input[["race_choice"]]) %>% 
    mutate(borough = fct_reorder(borough, abortion)) %>% 
    plot_ly(x = ~borough, y = ~abortion, color = ~borough, colors = "viridis", type = "bar") %>% 
    layout(
      xaxis = list(title = "County"),
      yaxis = list(title = 'Induced Abortions 
                   per 1,000 Live Births'))
}) 
```

